### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by mariochamdjoko** [geunzz/ArcFace#1]
Do you know if I can use LFW dataset for this training? If it's possible, could you give me the guide to prepare the LFW dataset to match the code you've provided?

**Comment by geunzz** [comment]
Hi,

Thank you for your interest.
I think you can use LFW dataset from kaggle.

https://www.kaggle.com/datasets/jessicali9530/lfw-dataset?resource=download-directory&select=lfw-deepfunneled

after unzip the dataset file, and input the directory path to
data_generator class which exists in dataset_generation.py file.
Then you can trim the data with class labels.

Thanks


2024년 6월 5일 (수) 오전 12:48, TanganHitam1 ***@***.***>님이 작성:

**Comment by mariochamdjoko** [comment]
Thankyou so much for the reply, it helps so much
